#!/usr/bin/env python3
"""Build the English and Arabic pages from the Swedish templates.

    python tools/build.py

The Swedish pages - index.html, webbdesign.html, integritet.html - are the
templates. Every piece of translatable text in them carries a data-i18n*
attribute naming a key in i18n.js. For each page and each language this:

  1. fills in the text from i18n.js
  2. builds the <head>: title, description, canonical address, the hreflang
     links that tell Google the three versions are one page in three
     languages, social-media preview tags, that language's fonts, and on the
     home page the business listing data
  3. builds the language switcher as links to the same page in the other
     languages
  4. writes Swedish back in place and the others to en/ and ar/

It also writes sitemap.xml and 404.html.

Running it twice gives the same result. If any text key is missing in any
language it stops with an error and writes nothing. Standard library only -
there is nothing to install. GitHub runs this automatically on every push
that changes the text or a template (.github/workflows/build-pages.yml).
"""
import html
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The one place the site's address is written down. Moving to a custom domain
# is a change here plus a rebuild.
SITE = "https://namarsandil.github.io/Elegant-Media/"

# Proves to Google Search Console that this site belongs to the studio
# (property: the SITE address above, added by the owner on 2026-09-18).
# Google re-checks it from time to time, so it has to stay. It is public by
# design - it only works for the Google account that created it. A move to a
# custom domain needs a new property and a new code here.
GOOGLE_SITE_VERIFICATION = "U59bcrzSS9EYo_qQybPawmnmjly41655PvMC7Fz8YPo"

LTR_FONTS = ("https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700"
             "&family=Jost:wght@300;400;500;600&display=swap")
# The wordmark is Latin Cormorant in every language, so Arabic needs that
# one weight as well.
RTL_FONTS = ("https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@700"
             "&family=El+Messiri:wght@400;600;700&family=Tajawal:wght@300;400;500;700&display=swap")

# Order matters: the first language is the default, served at the root.
LANGS = {
    "sv": {"dir": "ltr", "folder": "", "fonts": LTR_FONTS},
    "en": {"dir": "ltr", "folder": "en/", "fonts": LTR_FONTS},
    "ar": {"dir": "rtl", "folder": "ar/", "fonts": RTL_FONTS},
}
DEFAULT = "sv"
SWITCH_ORDER = ("ar", "en", "sv")          # left-to-right order of the switcher
SWITCH_LABEL = {"ar": "AR", "en": "EN", "sv": "SV"}

# template file -> which meta_* keys hold its title and description
PAGES = {
    "index.html": "home",
    "webbdesign.html": "wd",
    "integritet.html": "pp",
}

# Placeholder photography until the studio's own arrives - see assets/README.md.
OG_IMAGE = ("https://images.unsplash.com/photo-1519741497674-611481863552"
            "?w=1200&h=630&fit=crop&q=80")

# Business listing data (schema.org). The area is published, not the street
# address: the studio is run from a home.
BUSINESS = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "@id": SITE + "#business",
    "name": "ELEGANTMEDIA",
    "url": SITE,
    "image": OG_IMAGE,
    "telephone": "+46762000281",
    "email": "elegantmedia200@gmail.com",
    "address": {
        "@type": "PostalAddress",
        "addressLocality": "Spånga",
        "postalCode": "163 77",
        "addressRegion": "Stockholms län",
        "addressCountry": "SE",
    },
    "areaServed": ["Stockholm", "Stockholms län"],
    "knowsLanguage": ["sv", "en", "ar"],
    "sameAs": ["https://www.instagram.com/elegant.foto.video/"],
}

HEAD_SLOT = re.compile(r"(  <!-- build:head -->\n).*?(  <!-- /build:head -->)", re.S)
SWITCH_SLOT = re.compile(r"(<!-- build:lang-switch -->).*?(<!-- /build:lang-switch -->)", re.S)
GENERATED_BANNER = re.compile(r"<!--\n  GENERATED by tools/build\.py.*?-->\n", re.S)
TEMPLATE_BANNER = re.compile(r"<!--\n  This Swedish page is also the TEMPLATE.*?-->\n", re.S)


class BuildError(Exception):
    pass


# --------------------------------------------------------------- i18n.js

def load_translations():
    """Read i18n.js into {lang: {key: value}}.

    Relies on the file's layout: one `  xx: {` line opens each language, one
    key: 'value' pair (or several) per line, `  },` closes it. Values may be
    single- or double-quoted and use backslash escapes."""
    src = io.open(os.path.join(ROOT, "i18n.js"), encoding="utf-8").read()
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)       # drop comments
    pair = re.compile(r"""(\w+)\s*:\s*('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")""")
    out, lang = {}, None
    for line in src.split("\n"):
        m = re.match(r"^  (\w+): \{\s*$", line)
        if m:
            lang = m.group(1)
            out[lang] = {}
            continue
        if re.match(r"^  \},?\s*$", line):
            lang = None
            continue
        if lang:
            for key, raw in pair.findall(line):
                out[lang][key] = re.sub(r"\\(.)", r"\1", raw[1:-1])
    missing_langs = [l for l in LANGS if l not in out]
    if missing_langs:
        raise BuildError("i18n.js has no block for: " + ", ".join(missing_langs))
    return out


# ------------------------------------------------------------- filling text

def _matching_close(text, tag, start):
    """Index of the close tag that matches an already-opened <tag>."""
    depth, pos = 1, start
    pat = re.compile(r"<(/?)%s\b" % re.escape(tag), re.I)
    while depth:
        m = pat.search(text, pos)
        if not m:
            raise BuildError("unclosed <%s>" % tag)
        depth += -1 if m.group(1) else 1
        pos = m.end()
    return m.start()


def _set_attr(tag_html, name, value):
    """Set (or replace) one attribute on a start tag."""
    value = html.escape(value, quote=True)
    stripped = re.sub(r'\s%s="[^"]*"' % re.escape(name), "", tag_html)
    return re.sub(r"(\s*/?>)$", ' %s="%s"\\1' % (name, value), stripped, count=1)


def fill_text(page_html, strings, where):
    """Fill every data-i18n* hook from `strings`. Raises on a missing key."""
    missing = set()

    # Inner content. Hooks nested inside another hook are skipped: the outer
    # one's text replaces them anyway (this mirrors what the browser does).
    spans = []
    for m in re.finditer(r'<([a-z0-9]+)(?=[\s>])[^>]*\bdata-i18n="([a-z0-9_]+)"[^>]*>', page_html, re.I):
        spans.append((m.start(), m.end(), _matching_close(page_html, m.group(1), m.end()), m.group(2)))
    outer = [s for s in spans if not any(o[0] < s[0] and s[2] <= o[2] for o in spans if o is not s)]
    for _, inner_start, inner_end, key in sorted(outer, key=lambda s: -s[0]):
        if key not in strings:
            missing.add(key)
            continue
        page_html = page_html[:inner_start] + strings[key] + page_html[inner_end:]

    # Attributes: placeholder, aria-label, alt.
    for hook, attr in (("data-i18n-ph", "placeholder"), ("data-i18n-aria", "aria-label"),
                       ("data-i18n-alt", "alt")):
        def repl(m, attr=attr):
            key = m.group(1)
            if key not in strings:
                missing.add(key)
                return m.group(0)
            return _set_attr(m.group(0), attr, strings[key])
        page_html = re.sub(r'<[a-z0-9]+[^>]*\b%s="([a-z0-9_]+)"[^>]*>' % hook, repl, page_html, flags=re.I)

    if missing:
        raise BuildError("%s: missing text keys %s" % (where, ", ".join(sorted(missing))))
    return page_html


# ------------------------------------------------------------ addresses

def page_path(page):
    return "" if page == "index.html" else page


def absolute_url(page, lang):
    return SITE + LANGS[lang]["folder"] + page_path(page)


def relative_url(page, from_lang, to_lang):
    """Link from `page` in one language to the same page in another."""
    if from_lang == to_lang:
        return page_path(page) or "./"
    up = "../" if LANGS[from_lang]["folder"] else ""
    return (up + LANGS[to_lang]["folder"] + page_path(page)) or "./"


def rebase_assets(page_html):
    """For pages one folder down: point relative links at shared files
    (styles.css, script.js, favicons, assets/...) back up to the root. Links
    between the site's own pages stay as they are - they should stay inside
    the same language."""
    pages = tuple(PAGES)

    def fix(url):
        if re.match(r"^(#|[a-z][a-z0-9+.-]*:|/|\.\./)", url, re.I):
            return url                           # anchor, absolute, already rebased
        if url.split("#")[0] in pages or url in ("", "./"):
            return url
        return "../" + url

    def attr(m):
        return '%s="%s"' % (m.group(1), fix(m.group(2)))

    def srcset(m):
        parts = [p.strip() for p in m.group(1).split(",")]
        fixed = []
        for p in parts:
            bits = p.split(None, 1)
            fixed.append(" ".join([fix(bits[0])] + bits[1:]))
        return 'srcset="%s"' % ", ".join(fixed)

    page_html = re.sub(r'\b(src|href)="([^"]*)"', attr, page_html)
    return re.sub(r'\bsrcset="([^"]*)"', srcset, page_html)


# --------------------------------------------------------- generated parts

def head_block(page, lang, strings, t):
    meta = PAGES[page]
    title, desc = strings["meta_%s_title" % meta], strings["meta_%s_desc" % meta]
    url = absolute_url(page, lang)
    e = lambda s: html.escape(s, quote=True)
    lines = [
        "<!-- Generated by tools/build.py: edit the wording in i18n.js (meta_* keys). -->",
        "<title>%s</title>" % html.escape(title, quote=False),
        '<meta name="description" content="%s" />' % e(desc),
        '<link rel="canonical" href="%s" />' % url,
    ]
    # Google looks for this on the property's own address - the Swedish home.
    if page == "index.html" and lang == DEFAULT and GOOGLE_SITE_VERIFICATION:
        lines.insert(3, '<meta name="google-site-verification" content="%s" />'
                     % e(GOOGLE_SITE_VERIFICATION))
    for other in LANGS:
        lines.append('<link rel="alternate" hreflang="%s" href="%s" />' % (other, absolute_url(page, other)))
    lines.append('<link rel="alternate" hreflang="x-default" href="%s" />' % absolute_url(page, DEFAULT))
    lines += [
        "",
        '<meta property="og:type" content="website" />',
        '<meta property="og:site_name" content="ELEGANTMEDIA" />',
        '<meta property="og:locale" content="%s" />' % strings["_locale"],
    ]
    for other in LANGS:
        if other != lang:
            lines.append('<meta property="og:locale:alternate" content="%s" />' % t[other]["_locale"])
    lines += [
        '<meta property="og:title" content="%s" />' % e(title),
        '<meta property="og:description" content="%s" />' % e(desc),
        '<meta property="og:url" content="%s" />' % url,
        '<meta property="og:image" content="%s" />' % e(OG_IMAGE),
        '<meta property="og:image:width" content="1200" />',
        '<meta property="og:image:height" content="630" />',
        '<meta property="og:image:alt" content="%s" />' % e(strings["meta_og_alt"]),
        '<meta name="twitter:card" content="summary_large_image" />',
        "",
        "<!-- Only this language's two font families are downloaded. -->",
        '<link rel="preconnect" href="https://fonts.googleapis.com" />',
        '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />',
        '<link rel="stylesheet" href="%s" />' % e(LANGS[lang]["fonts"]),
    ]
    if page == "index.html":
        data = dict(BUSINESS, description=strings["meta_home_desc"])
        body = json.dumps(data, ensure_ascii=False, indent=2).replace("</", "<\\/")
        lines += ["", '<script type="application/ld+json">'] + body.split("\n") + ["</script>"]
    return "\n".join(("  " + l) if l else "" for l in lines) + "\n"


def switch_block(page, lang, strings):
    links = []
    for other in SWITCH_ORDER:
        current = other == lang
        links.append('<a class="lang-btn%s" href="%s" hreflang="%s" lang="%s"%s>%s</a>' % (
            " active" if current else "", relative_url(page, lang, other), other, other,
            ' aria-current="page"' if current else "", SWITCH_LABEL[other]))
    pad = "          "
    return ('\n%s<div class="lang-switch" id="langSwitch" role="group" data-i18n-aria="a11y_lang" aria-label="%s">\n'
            % (pad[:-2], html.escape(strings["a11y_lang"], quote=True))
            + "".join("%s%s\n" % (pad, l) for l in links) + pad[:-2] + "</div>\n" + pad[:-2])


def generated_banner(page):
    return ("<!--\n  GENERATED by tools/build.py from ../%s and ../i18n.js - do not edit.\n"
            "  Any change made here is overwritten by the next build.\n-->\n" % page)


# ------------------------------------------------------------------ build

def build_page(template, page, lang, t):
    strings = t[lang]
    where = "%s%s" % (LANGS[lang]["folder"], page)
    if not HEAD_SLOT.search(template) or not SWITCH_SLOT.search(template):
        raise BuildError(page + ": the build:head / build:lang-switch markers are missing")

    # start from empty slots, so rebuilding never nests old output
    out = HEAD_SLOT.sub(r"\1\2", template)
    out = SWITCH_SLOT.sub(r"\1\2", out)
    out = fill_text(out, strings, where)

    sub = bool(LANGS[lang]["folder"])
    root_attr = ' data-root="../"' if sub else ""
    out = re.sub(r"<html[^>]*>", '<html lang="%s" dir="%s"%s>' % (lang, strings["_dir"], root_attr), out, count=1)
    if sub:
        out = rebase_assets(out)
        out = TEMPLATE_BANNER.sub(lambda m: generated_banner(page), out, count=1)

    out = HEAD_SLOT.sub(lambda m: m.group(1) + head_block(page, lang, strings, t) + m.group(2), out)
    out = SWITCH_SLOT.sub(lambda m: m.group(1) + switch_block(page, lang, strings) + m.group(2), out)
    return out


def sitemap():
    rows = ['<?xml version="1.0" encoding="UTF-8"?>',
            "<!-- Generated by tools/build.py. Submit this address in Google Search Console. -->",
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" '
            'xmlns:xhtml="http://www.w3.org/1999/xhtml">']
    for page in PAGES:
        for lang in LANGS:
            rows.append("  <url>")
            rows.append("    <loc>%s</loc>" % absolute_url(page, lang))
            for other in LANGS:
                rows.append('    <xhtml:link rel="alternate" hreflang="%s" href="%s"/>' % (other, absolute_url(page, other)))
            rows.append('    <xhtml:link rel="alternate" hreflang="x-default" href="%s"/>' % absolute_url(page, DEFAULT))
            rows.append("  </url>")
    rows.append("</urlset>")
    return "\n".join(rows) + "\n"


def not_found_page():
    """GitHub Pages serves this for any missing address, at any depth, so it
    uses absolute links and carries its own styling."""
    return """<!DOCTYPE html>
<!-- Generated by tools/build.py - edit the build script, not this file. -->
<html lang="sv" dir="ltr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="noindex" />
  <meta name="theme-color" content="#0d0d0d" />
  <title>Sidan finns inte | ELEGANTMEDIA</title>
  <link rel="icon" href="%(site)sfavicon.svg" type="image/svg+xml" />
  <style>
    body { margin: 0; min-height: 100vh; display: grid; place-items: center; background: #0d0d0d;
           color: #c4c2bd; font: 17px/1.7 system-ui, -apple-system, "Segoe UI", sans-serif; text-align: center; }
    main { padding: 48px 24px; max-width: 34rem; }
    .mark { font: 700 1.7rem/1.1 Georgia, "Times New Roman", serif; letter-spacing: .22em;
            color: #e3c879; margin-bottom: 36px; }
    .mark small { display: block; font-size: .42em; letter-spacing: .3em; margin-top: 4px; }
    h1 { font: 600 1.6rem/1.3 Georgia, "Times New Roman", serif; color: #f5f4f1; margin: 0 0 8px; }
    p { margin: 0 0 28px; }
    .langs { display: grid; gap: 10px; }
    a { display: block; padding: 13px 20px; border: 1px solid rgba(201,162,75,.4); border-radius: 999px;
        color: #e3c879; text-decoration: none; }
    a:hover, a:focus-visible { background: #c9a24b; color: #0d0d0d; outline: none; }
  </style>
</head>
<body>
  <main>
    <div class="mark" aria-hidden="true">ELEGANT<small>MEDIA</small></div>
    <h1>Sidan finns inte</h1>
    <p>Adressen kan ha ändrats, eller innehålla ett skrivfel.</p>
    <p lang="en" dir="ltr">This page doesn't exist.</p>
    <p lang="ar" dir="rtl">هذه الصفحة غير موجودة.</p>
    <nav class="langs" aria-label="Startsida">
      <a href="%(site)s">Till startsidan</a>
      <a href="%(site)sen/" lang="en">Go to the home page</a>
      <a href="%(site)sar/" lang="ar" dir="rtl">الانتقال إلى الصفحة الرئيسية</a>
    </nav>
  </main>
</body>
</html>
""" % {"site": SITE}


def main():
    t = load_translations()
    outputs = {}
    for page in PAGES:
        path = os.path.join(ROOT, page)
        template = io.open(path, encoding="utf-8").read()
        for lang in LANGS:
            outputs[LANGS[lang]["folder"] + page] = build_page(template, page, lang, t)
    outputs["sitemap.xml"] = sitemap()
    outputs["404.html"] = not_found_page()

    # Everything built without error - only now touch the disk, and only
    # files whose content actually changed.
    changed = []
    for rel, content in outputs.items():
        path = os.path.join(ROOT, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        old = io.open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old != content:
            io.open(path, "w", encoding="utf-8", newline="").write(content)
            changed.append(rel)
    print("built %d files, %d changed%s" % (len(outputs), len(changed),
                                            (": " + ", ".join(changed)) if changed else ""))


if __name__ == "__main__":
    try:
        main()
    except BuildError as err:
        print("BUILD FAILED - nothing was written.\n" + str(err), file=sys.stderr)
        sys.exit(1)
